site_name: "Imageomics Guide"
site_description: "A guide to collaborative work for Imageomics, including GitHub and Hugging Face workflows."
site_author: "Imageomics Institute"
site_url: "https://thompsonmj.github.io/Imageomics-guide/" 

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - macros
  - search
  - glightbox

markdown_extensions:
  - pymdownx.tasklist
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true


nav:
  - Home: index.md
  - GitHub Guide:
      - "Repo Guide": wiki-guide/GitHub-Repo-Guide.md
      - "Workflow": wiki-guide/The-GitHub-Workflow.md
      - "Pull Request Guide": wiki-guide/The-GitHub-Pull-Request-(PR)-Guide.md
      - "Projects Guide": wiki-guide/Guide-to-GitHub-Projects.md
      - "Branch Protection": wiki-guide/When-to-think-about-branch-protections.md
      - "Two Repo Problem": wiki-guide/Two-Repo-Problem.md
  - Hugging Face Guide:
      - "Repo Guide": wiki-guide/Hugging-Face-Repo-Guide.md
      - "Workflow": wiki-guide/The-Hugging-Face-Workflow.md
      - "Dataset Upload Guide": wiki-guide/The-Hugging-Face-Dataset-Upload-Guide.md
  - Templates:
      - "Dataset Card Template": wiki-guide/HF_DatasetCard_Template_mkdocs.md
      - "Model Card Template": wiki-guide/HF_ModelCard_Template_mkdocs.md
  - Metadata Guide: wiki-guide/Metadata-Guide.md
  - Command Line Cheat Sheet: wiki-guide/Command-Line-Cheat-Sheet.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Other Resources:
      - "Glossary for Imageomics": wiki-guide/Glossary-for-Imageomics.md
      - "Virtual Environments": wiki-guide/Virtual-Environments.md
      - "Helpful Tools": wiki-guide/Helpful-Tools-for-your-Workflow.md
      - "Handling API Keys": wiki-guide/Handling-API-Keys.md
      - "Technical Infrastructure": wiki-guide/Technical-Infrastructure.md

# markdown_extensions:

#   - admonition
#   - toc:
#       permalink: true
#   - footnotes

# For extra custom styling
# extra_css:
#   - css/custom.css
